import { StyleSheet } from 'react-native';

export const theme = {
  colors: {
    background: '#0b0f10',
    surface: '#141b1f',
    surfaceAlt: '#1b252a',
    surfaceStrong: '#1f2b31',
    text: '#f5f7f9',
    textMuted: '#8a949c',
    accent: '#ffb454',
    accentStrong: '#ff8a3d',
    success: '#23d18b',
    danger: '#ff5d5d',
    border: '#253038',
    track: '#2a343a',
  },
  radius: {
    card: 18,
    pill: 999,
    button: 12,
  },
};

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  glowTop: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(255, 180, 84, 0.22)',
    top: -140,
    right: -80,
  },
  glowBottom: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: 'rgba(35, 209, 139, 0.18)',
    bottom: -160,
    left: -120,
  },
  content: {
    padding: 20,
    paddingTop: 56,
    paddingBottom: 80,
  },
  heroCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.card,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  eyebrow: {
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 2,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: theme.colors.text,
    fontFamily: 'serif',
  },
  subtitle: {
    color: theme.colors.textMuted,
    fontSize: 14,
    marginTop: 12,
    marginBottom: 16,
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statusPill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  statusPillReady: {
    borderColor: 'rgba(35, 209, 139, 0.6)',
  },
  statusPillActive: {
    backgroundColor: 'rgba(35, 209, 139, 0.2)',
    borderColor: 'rgba(35, 209, 139, 0.7)',
  },
  recordingStatusPill: {
    backgroundColor: 'rgba(255, 93, 93, 0.18)',
    borderColor: 'rgba(255, 93, 93, 0.7)',
  },
  statusPillDanger: {
    backgroundColor: 'rgba(255, 93, 93, 0.18)',
    borderColor: 'rgba(255, 93, 93, 0.7)',
  },
  statusText: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  primaryButton: {
    backgroundColor: theme.colors.accent,
    paddingVertical: 14,
    borderRadius: theme.radius.button,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#1b1206',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.card,
    padding: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: 18,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 26,
  },
  sectionHint: {
    color: theme.colors.textMuted,
    fontSize: 12,
  },
  sectionContent: {
    marginTop: 12,
  },
  headerTitleAction: {
    alignItems: 'flex-start',
    flexShrink: 1,
  },
  timePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
  },
  timeText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontFamily: 'monospace',
  },
  transportRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  formatRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  formatButton: {
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: theme.colors.surfaceAlt,
  },
  formatButtonActive: {
    borderColor: theme.colors.accent,
    backgroundColor: 'rgba(255, 180, 84, 0.18)',
  },
  formatButtonDisabled: {
    opacity: 0.5,
  },
  formatButtonText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  formatButtonTextActive: {
    color: theme.colors.accent,
  },
  effectsToggle: {
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: theme.colors.surfaceAlt,
  },
  effectsToggleActive: {
    borderColor: 'rgba(35, 209, 139, 0.7)',
    backgroundColor: 'rgba(35, 209, 139, 0.2)',
  },
  effectsToggleText: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  controlButton: {
    backgroundColor: theme.colors.surfaceStrong,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: theme.radius.button,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minWidth: 96,
    alignItems: 'center',
  },
  controlButtonDisabled: {
    opacity: 0.5,
  },
  controlButtonText: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  recordButton: {
    backgroundColor: 'rgba(255, 180, 84, 0.18)',
    borderColor: 'rgba(255, 180, 84, 0.6)',
  },
  recordButtonText: {
    color: theme.colors.accent,
  },
  stopButton: {
    backgroundColor: 'rgba(255, 93, 93, 0.18)',
    borderColor: 'rgba(255, 93, 93, 0.6)',
  },
  stopButtonText: {
    color: theme.colors.danger,
  },
  cancelButton: {
    backgroundColor: 'rgba(255, 93, 93, 0.15)',
    borderColor: 'rgba(255, 93, 93, 0.6)',
  },
  cancelButtonText: {
    color: theme.colors.danger,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.track,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: theme.colors.accentStrong,
  },
  levelFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: theme.colors.success,
  },
  progressMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  testSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  progressPercent: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  extractionDetails: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: theme.radius.button,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  testEntry: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: theme.radius.button,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginBottom: 10,
  },
  testEntryPass: {
    borderColor: 'rgba(35, 209, 139, 0.8)',
  },
  testEntryFail: {
    borderColor: 'rgba(255, 93, 93, 0.8)',
  },
  testEntryPending: {
    borderColor: 'rgba(255, 180, 84, 0.8)',
  },
  testEntryUnexpected: {
    borderColor: 'rgba(138, 148, 156, 0.6)',
  },
  testEntryTitle: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  testEntryMeta: {
    color: theme.colors.textMuted,
    fontSize: 12,
  },
  detailLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  detailValue: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '600',
  },
  detailPath: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginTop: 6,
    marginBottom: 8,
  },
  exportActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resetButton: {
    backgroundColor: 'rgba(255, 180, 84, 0.15)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: theme.radius.button,
    borderWidth: 1,
    borderColor: 'rgba(255, 180, 84, 0.6)',
    minWidth: 96,
    alignItems: 'center',
  },
  resetButtonText: {
    color: theme.colors.accent,
    fontSize: 14,
    fontWeight: '600',
  },
  controlGroup: {
    marginVertical: 10,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  label: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  valuePill: {
    color: theme.colors.textMuted,
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
    overflow: 'hidden',
  },
  iconResetButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceStrong,
  },
  iconResetButtonDisabled: {
    opacity: 0.4,
  },
  iconResetText: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  testList: {
    gap: 12,
  },
  testRow: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: theme.radius.button,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  testRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  testName: {
    color: theme.colors.text,
    fontSize: 14,
    fontWeight: '700',
    flexShrink: 1,
  },
  testError: {
    color: theme.colors.danger,
    fontSize: 12,
    marginTop: 6,
  },
  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 6,
  },
  metricKey: {
    color: theme.colors.textMuted,
    fontSize: 12,
  },
  metricValue: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'right',
    flexShrink: 1,
  },
  slider: {
    width: '100%',
    height: 40,
  },
  trackCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.card,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: 14,
  },
  trackHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  trackName: {
    color: theme.colors.text,
    fontSize: 17,
    fontWeight: '700',
  },
  trackMeta: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  trackButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  trackButton: {
    backgroundColor: theme.colors.surfaceStrong,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  trackButtonMuted: {
    backgroundColor: 'rgba(255, 93, 93, 0.2)',
    borderColor: 'rgba(255, 93, 93, 0.8)',
  },
  trackButtonSolo: {
    backgroundColor: 'rgba(35, 209, 139, 0.2)',
    borderColor: 'rgba(35, 209, 139, 0.8)',
  },
  trackButtonText: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
});
